"""email verification and pickup_eta

Revision ID: 2a104d67df7c
Revises: 5efb9f55b219
Create Date: 2026-07-11 00:28:04.846821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a104d67df7c'
down_revision: Union[str, None] = '5efb9f55b219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stringing_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_eta', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('verification_code_hash', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('verification_expires_at', sa.DateTime(), nullable=True))

    # Existing accounts predate email verification — treat them as verified so
    # nobody gets locked out on deploy.
    op.execute("UPDATE users SET email_verified = true")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verification_expires_at')
        batch_op.drop_column('verification_code_hash')
        batch_op.drop_column('email_verified')

    with op.batch_alter_table('stringing_jobs', schema=None) as batch_op:
        batch_op.drop_column('pickup_eta')

    # ### end Alembic commands ###
