"""add tension to stringing_jobs

Revision ID: 5efb9f55b219
Revises: 7e00900fae85
Create Date: 2026-07-10 21:23:53.738453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5efb9f55b219'
down_revision: Union[str, None] = '7e00900fae85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stringing_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tension', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stringing_jobs', schema=None) as batch_op:
        batch_op.drop_column('tension')

    # ### end Alembic commands ###
